//! Central deterministic resource-budget model.

use crate::diagnostics::{AgentError, AgentResult, ErrorCode};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::BTreeMap;

/// A bounded resource category shared across AgentIR layers.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResourceKind {
    /// Encoded bytes in one JSONL request.
    JsonlRequestBytes,
    /// Actions in one atomic transaction.
    ActionsPerTransaction,
    /// Declared dimensions in one program.
    DimensionsPerProgram,
    /// Top-level operations in one program.
    OperationsPerProgram,
    /// SSA values in one program.
    ValuesPerProgram,
    /// Typed holes in one program.
    HolesPerProgram,
    /// Proof obligations in one program.
    ObligationsPerProgram,
    /// Shape constraints in one program.
    ConstraintsPerProgram,
    /// Block arguments in one inline region.
    RegionArguments,
    /// Local operations in one inline region.
    RegionOperations,
    /// Operands on one top-level or region operation.
    OperandsPerOperation,
    /// Encoded JSON bytes in one action or operation attribute map.
    AttributeJsonBytes,
    /// Maximum structural JSON nesting depth.
    JsonNestingDepth,
    /// Named outputs in one program.
    OutputCount,
    /// Encoded bytes in one workspace archive.
    ArchiveBytes,
    /// Immutable revisions in one archive.
    RevisionsPerArchive,
    /// Replayable events in one archive.
    EventsPerArchive,
    /// Total ActionIR actions replayed from one archive.
    ActionsReplayedPerArchive,
    /// Bytes in exact-state or semantic canonical output.
    CanonicalOutputBytes,
    /// Elements in one evaluation tensor.
    EvaluationTensorElements,
    /// Total tensor elements materialized during one evaluation.
    TotalEvaluationElements,
    /// Nodes/items generated by one property or fuzz case.
    GeneratedCaseSize,
}

/// Configurable interactive limits. These values never enter graph or archive hashes.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResourceLimits {
    /// Maximum encoded JSONL request bytes.
    pub jsonl_request_bytes: u64,
    /// Maximum actions in one transaction.
    pub actions_per_transaction: u64,
    /// Maximum declared dimensions in a program.
    pub dimensions_per_program: u64,
    /// Maximum top-level operations in a program.
    pub operations_per_program: u64,
    /// Maximum SSA values in a program.
    pub values_per_program: u64,
    /// Maximum typed holes in a program.
    pub holes_per_program: u64,
    /// Maximum proof obligations in a program.
    pub obligations_per_program: u64,
    /// Maximum retained constraints in a program.
    pub constraints_per_program: u64,
    /// Maximum block arguments in one region.
    pub region_arguments: u64,
    /// Maximum local operations in one region.
    pub region_operations: u64,
    /// Maximum operands on one operation.
    pub operands_per_operation: u64,
    /// Maximum encoded attribute bytes on one operation.
    pub attribute_json_bytes: u64,
    /// Maximum JSON nesting depth.
    pub json_nesting_depth: u64,
    /// Maximum named outputs in a program.
    pub output_count: u64,
    /// Maximum encoded archive bytes.
    pub archive_bytes: u64,
    /// Maximum revisions in an archive.
    pub revisions_per_archive: u64,
    /// Maximum events in an archive.
    pub events_per_archive: u64,
    /// Maximum actions replayed from an archive.
    pub actions_replayed_per_archive: u64,
    /// Maximum canonical encoding bytes.
    pub canonical_output_bytes: u64,
    /// Maximum elements in one evaluation tensor.
    pub evaluation_tensor_elements: u64,
    /// Maximum total tensor elements materialized by one evaluation.
    pub total_evaluation_elements: u64,
    /// Maximum generated property/fuzz case size.
    pub generated_case_size: u64,
}

impl Default for ResourceLimits {
    fn default() -> Self {
        Self {
            jsonl_request_bytes: 1024 * 1024,
            actions_per_transaction: 4_096,
            dimensions_per_program: 4_096,
            operations_per_program: 100_000,
            values_per_program: 120_000,
            holes_per_program: 10_000,
            obligations_per_program: 100_000,
            constraints_per_program: 20_000,
            region_arguments: 64,
            region_operations: 1_024,
            operands_per_operation: 64,
            attribute_json_bytes: 256 * 1024,
            json_nesting_depth: 128,
            output_count: 1_024,
            archive_bytes: 64 * 1024 * 1024,
            revisions_per_archive: 100_000,
            events_per_archive: 100_000,
            actions_replayed_per_archive: 1_000_000,
            canonical_output_bytes: 64 * 1024 * 1024,
            evaluation_tensor_elements: 10_000_000,
            total_evaluation_elements: 50_000_000,
            generated_case_size: 10_000,
        }
    }
}

impl ResourceLimits {
    /// Returns non-configurable caps used while decoding and replaying archives.
    #[must_use]
    pub const fn hard_safety_caps() -> Self {
        Self {
            jsonl_request_bytes: 8 * 1024 * 1024,
            actions_per_transaction: 100_000,
            dimensions_per_program: 100_000,
            operations_per_program: 1_000_000,
            values_per_program: 1_200_000,
            holes_per_program: 100_000,
            obligations_per_program: 1_000_000,
            constraints_per_program: 200_000,
            region_arguments: 1_024,
            region_operations: 100_000,
            operands_per_operation: 4_096,
            attribute_json_bytes: 4 * 1024 * 1024,
            json_nesting_depth: 256,
            output_count: 100_000,
            archive_bytes: 64 * 1024 * 1024,
            revisions_per_archive: 250_000,
            events_per_archive: 250_000,
            actions_replayed_per_archive: 5_000_000,
            canonical_output_bytes: 128 * 1024 * 1024,
            evaluation_tensor_elements: 100_000_000,
            total_evaluation_elements: 500_000_000,
            generated_case_size: 100_000,
        }
    }

    /// Returns the configured limit for one resource kind.
    #[must_use]
    pub const fn limit(&self, resource: ResourceKind) -> u64 {
        match resource {
            ResourceKind::JsonlRequestBytes => self.jsonl_request_bytes,
            ResourceKind::ActionsPerTransaction => self.actions_per_transaction,
            ResourceKind::DimensionsPerProgram => self.dimensions_per_program,
            ResourceKind::OperationsPerProgram => self.operations_per_program,
            ResourceKind::ValuesPerProgram => self.values_per_program,
            ResourceKind::HolesPerProgram => self.holes_per_program,
            ResourceKind::ObligationsPerProgram => self.obligations_per_program,
            ResourceKind::ConstraintsPerProgram => self.constraints_per_program,
            ResourceKind::RegionArguments => self.region_arguments,
            ResourceKind::RegionOperations => self.region_operations,
            ResourceKind::OperandsPerOperation => self.operands_per_operation,
            ResourceKind::AttributeJsonBytes => self.attribute_json_bytes,
            ResourceKind::JsonNestingDepth => self.json_nesting_depth,
            ResourceKind::OutputCount => self.output_count,
            ResourceKind::ArchiveBytes => self.archive_bytes,
            ResourceKind::RevisionsPerArchive => self.revisions_per_archive,
            ResourceKind::EventsPerArchive => self.events_per_archive,
            ResourceKind::ActionsReplayedPerArchive => self.actions_replayed_per_archive,
            ResourceKind::CanonicalOutputBytes => self.canonical_output_bytes,
            ResourceKind::EvaluationTensorElements => self.evaluation_tensor_elements,
            ResourceKind::TotalEvaluationElements => self.total_evaluation_elements,
            ResourceKind::GeneratedCaseSize => self.generated_case_size,
        }
    }
}

/// Deterministic observed resource usage keyed by category.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResourceUsage {
    /// Observed or projected values.
    pub values: BTreeMap<ResourceKind, u64>,
}

impl ResourceUsage {
    /// Records one observed or projected resource value.
    pub fn record(&mut self, resource: ResourceKind, value: u64) {
        self.values.insert(resource, value);
    }
}

/// Stateless helper for consistent structured budget checks.
pub struct BudgetCheck;

impl BudgetCheck {
    /// Accepts `actual <= limit` and returns a structured deterministic error otherwise.
    pub fn ensure(
        resource: ResourceKind,
        limit: u64,
        actual: u64,
        context: impl Into<String>,
    ) -> AgentResult<()> {
        if actual <= limit {
            return Ok(());
        }
        let context = context.into();
        Err(AgentError::new(
            ErrorCode::ResourceLimitExceeded,
            format!("resource limit exceeded for {resource:?}"),
        )
        .with_types(json!(limit), json!(actual))
        .with_detail("resource", json!(resource))
        .with_detail("configured_limit", limit)
        .with_detail("attempted", actual)
        .with_detail("context", context)
        .with_repair("reduce the request or raise the configured interactive limit"))
    }

    /// Checks an observed value against the corresponding configured limit.
    pub fn against(
        limits: &ResourceLimits,
        resource: ResourceKind,
        actual: u64,
        context: impl Into<String>,
    ) -> AgentResult<()> {
        Self::ensure(resource, limits.limit(resource), actual, context)
    }
}
