//! Central deterministic resource-budget model.

use crate::diagnostics::{AgentError, AgentResult, ErrorCode};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::BTreeMap;

/// A bounded resource category shared across AgentIR layers.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResourceKind {
    /// Encoded bytes in one JSONL request.
    JsonlRequestBytes,
    /// Actions in one atomic transaction.
    ActionsPerTransaction,
    /// Declared dimensions in one program.
    DimensionsPerProgram,
    /// Top-level operations in one program.
    OperationsPerProgram,
    /// SSA values in one program.
    ValuesPerProgram,
    /// Typed holes in one program.
    HolesPerProgram,
    /// Proof obligations in one program.
    ObligationsPerProgram,
    /// Shape constraints in one program.
    ConstraintsPerProgram,
    /// Block arguments in one inline region.
    RegionArguments,
    /// Local operations in one inline region.
    RegionOperations,
    /// Operands on one top-level or region operation.
    OperandsPerOperation,
    /// Encoded JSON bytes in one action or operation attribute map.
    AttributeJsonBytes,
    /// Maximum structural JSON nesting depth.
    JsonNestingDepth,
    /// Named outputs in one program.
    OutputCount,
    /// Encoded bytes in one workspace archive.
    ArchiveBytes,
    /// Immutable revisions in one archive.
    RevisionsPerArchive,
    /// Replayable events in one archive.
    EventsPerArchive,
    /// Total ActionIR actions replayed from one archive.
    ActionsReplayedPerArchive,
    /// Bytes in exact-state or semantic canonical output.
    CanonicalOutputBytes,
    /// Elements in one evaluation tensor.
    EvaluationTensorElements,
    /// Total tensor elements materialized during one evaluation.
    TotalEvaluationElements,
    /// Nodes/items generated by one property or fuzz case.
    GeneratedCaseSize,
    /// Implementation candidates retained by one workspace.
    CandidatesPerWorkspace,
    /// Immutable candidate revisions retained by one workspace.
    CandidateRevisionsPerWorkspace,
    /// Candidate events retained by one archive.
    CandidateEventsPerArchive,
    /// Candidate actions in one atomic transaction.
    CandidateActionsPerTransaction,
    /// Top-level operations in one ImplIR graph.
    ImplOperations,
    /// SSA values in one ImplIR graph.
    ImplValues,
    /// Candidate branch identities retained by one workspace.
    CandidateBranches,
    /// Rewrite matches emitted by one continuation.
    RewriteMatchesPerContinuation,
    /// Trusted rewrite steps in one candidate proof chain.
    RewriteStepsPerCandidate,
    /// Evidence records retained by one workspace.
    EvidenceRecords,
    /// Encoded EvidenceIR bytes retained by one workspace.
    EvidenceBytes,
    /// Open candidate equivalence obligations.
    OpenEquivalenceObligations,
    /// Deterministic cases in one differential validation.
    DifferentialCases,
    /// Tensor elements generated by one differential validation.
    DifferentialTensorElements,
    /// Exact or semantic candidate canonical bytes.
    CandidateCanonicalBytes,
    /// Exact speculative/guarded candidate canonical-v2 bytes.
    CandidateCanonicalV2Bytes,
    /// Nodes/items generated by one candidate property case.
    GeneratedCandidateCaseSize,
    /// Persistent proposal records retained by one workspace.
    ProposalsPerWorkspace,
    /// Persistent proposals reachable on one candidate branch.
    ProposalsPerCandidate,
    /// Proposal actions in one speculative transaction.
    ProposalActionsPerTransaction,
    /// Operations in one proposed replacement fragment.
    ProposalFragmentOperations,
    /// Values in one proposed replacement fragment.
    ProposalFragmentValues,
    /// Encoded normalized proposal bytes.
    ProposalEncodedBytes,
    /// Speculative nodes retained on one candidate branch.
    SpeculativeNodesPerCandidate,
    /// Consecutive speculative depth on one branch.
    SpeculativeDepthPerBranch,
    /// Unknown actions retained on one branch.
    UnknownActionsPerBranch,
    /// Ordered open/unsupported proof-debt items.
    OpenProofDebtObligations,
    /// Translation-validation attempts retained by one workspace.
    TranslationValidationAttempts,
    /// Deterministic validator work units in one check.
    TranslationValidationWorkUnits,
    /// Guarded candidate revisions retained by one workspace.
    GuardedCandidates,
    /// Nodes needed to compute one guard predicate.
    GuardDependencyNodes,
    /// Maximum recursive fallback depth.
    FallbackDepth,
    /// Encoded bytes in one deterministic counterexample.
    CounterexampleBytes,
    /// Candidate-semantics-v2 events retained by one archive.
    CandidateSemanticsV2Events,
    /// Generated speculative property-case size.
    GeneratedSpeculativeCaseSize,
}

/// Configurable interactive limits. These values never enter graph or archive hashes.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResourceLimits {
    /// Maximum encoded JSONL request bytes.
    pub jsonl_request_bytes: u64,
    /// Maximum actions in one transaction.
    pub actions_per_transaction: u64,
    /// Maximum declared dimensions in a program.
    pub dimensions_per_program: u64,
    /// Maximum top-level operations in a program.
    pub operations_per_program: u64,
    /// Maximum SSA values in a program.
    pub values_per_program: u64,
    /// Maximum typed holes in a program.
    pub holes_per_program: u64,
    /// Maximum proof obligations in a program.
    pub obligations_per_program: u64,
    /// Maximum retained constraints in a program.
    pub constraints_per_program: u64,
    /// Maximum block arguments in one region.
    pub region_arguments: u64,
    /// Maximum local operations in one region.
    pub region_operations: u64,
    /// Maximum operands on one operation.
    pub operands_per_operation: u64,
    /// Maximum encoded attribute bytes on one operation.
    pub attribute_json_bytes: u64,
    /// Maximum JSON nesting depth.
    pub json_nesting_depth: u64,
    /// Maximum named outputs in a program.
    pub output_count: u64,
    /// Maximum encoded archive bytes.
    pub archive_bytes: u64,
    /// Maximum revisions in an archive.
    pub revisions_per_archive: u64,
    /// Maximum events in an archive.
    pub events_per_archive: u64,
    /// Maximum actions replayed from an archive.
    pub actions_replayed_per_archive: u64,
    /// Maximum canonical encoding bytes.
    pub canonical_output_bytes: u64,
    /// Maximum elements in one evaluation tensor.
    pub evaluation_tensor_elements: u64,
    /// Maximum total tensor elements materialized by one evaluation.
    pub total_evaluation_elements: u64,
    /// Maximum generated property/fuzz case size.
    pub generated_case_size: u64,
    /// Maximum implementation candidates in one workspace.
    pub candidates_per_workspace: u64,
    /// Maximum immutable candidate revisions in one workspace.
    pub candidate_revisions_per_workspace: u64,
    /// Maximum candidate events in one archive.
    pub candidate_events_per_archive: u64,
    /// Maximum actions in one candidate transaction.
    pub candidate_actions_per_transaction: u64,
    /// Maximum operations in one ImplIR graph.
    pub impl_operations: u64,
    /// Maximum values in one ImplIR graph.
    pub impl_values: u64,
    /// Maximum candidate branch identities in one workspace.
    pub candidate_branches: u64,
    /// Maximum emitted rewrite matches in one continuation.
    pub rewrite_matches_per_continuation: u64,
    /// Maximum trusted rewrite steps in one candidate.
    pub rewrite_steps_per_candidate: u64,
    /// Maximum evidence records in one workspace.
    pub evidence_records: u64,
    /// Maximum encoded evidence bytes in one workspace.
    pub evidence_bytes: u64,
    /// Maximum open equivalence obligations in one workspace.
    pub open_equivalence_obligations: u64,
    /// Maximum cases in one differential validation.
    pub differential_cases: u64,
    /// Maximum generated tensor elements in one differential validation.
    pub differential_tensor_elements: u64,
    /// Maximum bytes in candidate canonical encodings.
    pub candidate_canonical_bytes: u64,
    /// Maximum bytes in speculative/guarded candidate canonical-v2 encodings.
    pub candidate_canonical_v2_bytes: u64,
    /// Maximum nodes/items in one generated candidate/property case.
    pub generated_candidate_case_size: u64,
    /// Maximum persistent proposal records in one workspace.
    pub proposals_per_workspace: u64,
    /// Maximum proposals in one candidate history.
    pub proposals_per_candidate: u64,
    /// Maximum actions in one proposal transaction.
    pub proposal_actions_per_transaction: u64,
    /// Maximum operations in one proposed fragment.
    pub proposal_fragment_operations: u64,
    /// Maximum values in one proposed fragment.
    pub proposal_fragment_values: u64,
    /// Maximum encoded normalized proposal bytes.
    pub proposal_encoded_bytes: u64,
    /// Maximum speculative nodes in one candidate.
    pub speculative_nodes_per_candidate: u64,
    /// Maximum speculative depth on one branch.
    pub speculative_depth_per_branch: u64,
    /// Maximum unknown actions on one branch.
    pub unknown_actions_per_branch: u64,
    /// Maximum open or unsupported proof-debt obligations.
    pub open_proof_debt_obligations: u64,
    /// Maximum translation-validation attempts in one workspace.
    pub translation_validation_attempts: u64,
    /// Maximum deterministic work units in one translation check.
    pub translation_validation_work_units: u64,
    /// Maximum guarded candidate revisions in one workspace.
    pub guarded_candidates: u64,
    /// Maximum dependency nodes for one guard.
    pub guard_dependency_nodes: u64,
    /// Maximum guarded fallback recursion depth.
    pub fallback_depth: u64,
    /// Maximum encoded bytes in one counterexample.
    pub counterexample_bytes: u64,
    /// Maximum candidate-semantics-v2 events per archive.
    pub candidate_semantics_v2_events: u64,
    /// Maximum generated speculative property-case size.
    pub generated_speculative_case_size: u64,
}

impl Default for ResourceLimits {
    fn default() -> Self {
        Self {
            jsonl_request_bytes: 1024 * 1024,
            actions_per_transaction: 4_096,
            dimensions_per_program: 4_096,
            operations_per_program: 100_000,
            values_per_program: 120_000,
            holes_per_program: 10_000,
            obligations_per_program: 100_000,
            constraints_per_program: 20_000,
            region_arguments: 64,
            region_operations: 1_024,
            operands_per_operation: 64,
            attribute_json_bytes: 256 * 1024,
            json_nesting_depth: 128,
            output_count: 1_024,
            archive_bytes: 64 * 1024 * 1024,
            revisions_per_archive: 100_000,
            events_per_archive: 100_000,
            actions_replayed_per_archive: 1_000_000,
            canonical_output_bytes: 64 * 1024 * 1024,
            evaluation_tensor_elements: 10_000_000,
            total_evaluation_elements: 50_000_000,
            generated_case_size: 10_000,
            candidates_per_workspace: 10_000,
            candidate_revisions_per_workspace: 100_000,
            candidate_events_per_archive: 100_000,
            candidate_actions_per_transaction: 1_024,
            impl_operations: 100_000,
            impl_values: 120_000,
            candidate_branches: 10_000,
            rewrite_matches_per_continuation: 10_000,
            rewrite_steps_per_candidate: 10_000,
            evidence_records: 100_000,
            evidence_bytes: 64 * 1024 * 1024,
            open_equivalence_obligations: 10_000,
            differential_cases: 256,
            differential_tensor_elements: 1_000_000,
            candidate_canonical_bytes: 64 * 1024 * 1024,
            candidate_canonical_v2_bytes: 64 * 1024 * 1024,
            generated_candidate_case_size: 10_000,
            proposals_per_workspace: 100_000,
            proposals_per_candidate: 1_024,
            proposal_actions_per_transaction: 1_024,
            proposal_fragment_operations: 1_024,
            proposal_fragment_values: 1_024,
            proposal_encoded_bytes: 1024 * 1024,
            speculative_nodes_per_candidate: 10_000,
            speculative_depth_per_branch: 128,
            unknown_actions_per_branch: 128,
            open_proof_debt_obligations: 128,
            translation_validation_attempts: 100_000,
            translation_validation_work_units: 100_000,
            guarded_candidates: 10_000,
            guard_dependency_nodes: 1_024,
            fallback_depth: 16,
            counterexample_bytes: 1024 * 1024,
            candidate_semantics_v2_events: 100_000,
            generated_speculative_case_size: 10_000,
        }
    }
}

impl ResourceLimits {
    /// Returns non-configurable caps used while decoding and replaying archives.
    #[must_use]
    pub const fn hard_safety_caps() -> Self {
        Self {
            jsonl_request_bytes: 8 * 1024 * 1024,
            actions_per_transaction: 100_000,
            dimensions_per_program: 100_000,
            operations_per_program: 1_000_000,
            values_per_program: 1_200_000,
            holes_per_program: 100_000,
            obligations_per_program: 1_000_000,
            constraints_per_program: 200_000,
            region_arguments: 1_024,
            region_operations: 100_000,
            operands_per_operation: 4_096,
            attribute_json_bytes: 4 * 1024 * 1024,
            json_nesting_depth: 256,
            output_count: 100_000,
            archive_bytes: 64 * 1024 * 1024,
            revisions_per_archive: 250_000,
            events_per_archive: 250_000,
            actions_replayed_per_archive: 5_000_000,
            canonical_output_bytes: 128 * 1024 * 1024,
            evaluation_tensor_elements: 100_000_000,
            total_evaluation_elements: 500_000_000,
            generated_case_size: 100_000,
            candidates_per_workspace: 100_000,
            candidate_revisions_per_workspace: 250_000,
            candidate_events_per_archive: 250_000,
            candidate_actions_per_transaction: 100_000,
            impl_operations: 1_000_000,
            impl_values: 1_200_000,
            candidate_branches: 100_000,
            rewrite_matches_per_continuation: 100_000,
            rewrite_steps_per_candidate: 100_000,
            evidence_records: 1_000_000,
            evidence_bytes: 128 * 1024 * 1024,
            open_equivalence_obligations: 100_000,
            differential_cases: 10_000,
            differential_tensor_elements: 100_000_000,
            candidate_canonical_bytes: 128 * 1024 * 1024,
            candidate_canonical_v2_bytes: 128 * 1024 * 1024,
            generated_candidate_case_size: 100_000,
            proposals_per_workspace: 1_000_000,
            proposals_per_candidate: 100_000,
            proposal_actions_per_transaction: 100_000,
            proposal_fragment_operations: 100_000,
            proposal_fragment_values: 100_000,
            proposal_encoded_bytes: 8 * 1024 * 1024,
            speculative_nodes_per_candidate: 100_000,
            speculative_depth_per_branch: 1_024,
            unknown_actions_per_branch: 1_024,
            open_proof_debt_obligations: 100_000,
            translation_validation_attempts: 1_000_000,
            translation_validation_work_units: 1_000_000,
            guarded_candidates: 100_000,
            guard_dependency_nodes: 100_000,
            fallback_depth: 64,
            counterexample_bytes: 8 * 1024 * 1024,
            candidate_semantics_v2_events: 250_000,
            generated_speculative_case_size: 100_000,
        }
    }

    /// Returns the configured limit for one resource kind.
    #[must_use]
    pub const fn limit(&self, resource: ResourceKind) -> u64 {
        match resource {
            ResourceKind::JsonlRequestBytes => self.jsonl_request_bytes,
            ResourceKind::ActionsPerTransaction => self.actions_per_transaction,
            ResourceKind::DimensionsPerProgram => self.dimensions_per_program,
            ResourceKind::OperationsPerProgram => self.operations_per_program,
            ResourceKind::ValuesPerProgram => self.values_per_program,
            ResourceKind::HolesPerProgram => self.holes_per_program,
            ResourceKind::ObligationsPerProgram => self.obligations_per_program,
            ResourceKind::ConstraintsPerProgram => self.constraints_per_program,
            ResourceKind::RegionArguments => self.region_arguments,
            ResourceKind::RegionOperations => self.region_operations,
            ResourceKind::OperandsPerOperation => self.operands_per_operation,
            ResourceKind::AttributeJsonBytes => self.attribute_json_bytes,
            ResourceKind::JsonNestingDepth => self.json_nesting_depth,
            ResourceKind::OutputCount => self.output_count,
            ResourceKind::ArchiveBytes => self.archive_bytes,
            ResourceKind::RevisionsPerArchive => self.revisions_per_archive,
            ResourceKind::EventsPerArchive => self.events_per_archive,
            ResourceKind::ActionsReplayedPerArchive => self.actions_replayed_per_archive,
            ResourceKind::CanonicalOutputBytes => self.canonical_output_bytes,
            ResourceKind::EvaluationTensorElements => self.evaluation_tensor_elements,
            ResourceKind::TotalEvaluationElements => self.total_evaluation_elements,
            ResourceKind::GeneratedCaseSize => self.generated_case_size,
            ResourceKind::CandidatesPerWorkspace => self.candidates_per_workspace,
            ResourceKind::CandidateRevisionsPerWorkspace => self.candidate_revisions_per_workspace,
            ResourceKind::CandidateEventsPerArchive => self.candidate_events_per_archive,
            ResourceKind::CandidateActionsPerTransaction => self.candidate_actions_per_transaction,
            ResourceKind::ImplOperations => self.impl_operations,
            ResourceKind::ImplValues => self.impl_values,
            ResourceKind::CandidateBranches => self.candidate_branches,
            ResourceKind::RewriteMatchesPerContinuation => self.rewrite_matches_per_continuation,
            ResourceKind::RewriteStepsPerCandidate => self.rewrite_steps_per_candidate,
            ResourceKind::EvidenceRecords => self.evidence_records,
            ResourceKind::EvidenceBytes => self.evidence_bytes,
            ResourceKind::OpenEquivalenceObligations => self.open_equivalence_obligations,
            ResourceKind::DifferentialCases => self.differential_cases,
            ResourceKind::DifferentialTensorElements => self.differential_tensor_elements,
            ResourceKind::CandidateCanonicalBytes => self.candidate_canonical_bytes,
            ResourceKind::CandidateCanonicalV2Bytes => self.candidate_canonical_v2_bytes,
            ResourceKind::GeneratedCandidateCaseSize => self.generated_candidate_case_size,
            ResourceKind::ProposalsPerWorkspace => self.proposals_per_workspace,
            ResourceKind::ProposalsPerCandidate => self.proposals_per_candidate,
            ResourceKind::ProposalActionsPerTransaction => self.proposal_actions_per_transaction,
            ResourceKind::ProposalFragmentOperations => self.proposal_fragment_operations,
            ResourceKind::ProposalFragmentValues => self.proposal_fragment_values,
            ResourceKind::ProposalEncodedBytes => self.proposal_encoded_bytes,
            ResourceKind::SpeculativeNodesPerCandidate => self.speculative_nodes_per_candidate,
            ResourceKind::SpeculativeDepthPerBranch => self.speculative_depth_per_branch,
            ResourceKind::UnknownActionsPerBranch => self.unknown_actions_per_branch,
            ResourceKind::OpenProofDebtObligations => self.open_proof_debt_obligations,
            ResourceKind::TranslationValidationAttempts => self.translation_validation_attempts,
            ResourceKind::TranslationValidationWorkUnits => self.translation_validation_work_units,
            ResourceKind::GuardedCandidates => self.guarded_candidates,
            ResourceKind::GuardDependencyNodes => self.guard_dependency_nodes,
            ResourceKind::FallbackDepth => self.fallback_depth,
            ResourceKind::CounterexampleBytes => self.counterexample_bytes,
            ResourceKind::CandidateSemanticsV2Events => self.candidate_semantics_v2_events,
            ResourceKind::GeneratedSpeculativeCaseSize => self.generated_speculative_case_size,
        }
    }
}

/// Deterministic observed resource usage keyed by category.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResourceUsage {
    /// Observed or projected values.
    pub values: BTreeMap<ResourceKind, u64>,
}

impl ResourceUsage {
    /// Records one observed or projected resource value.
    pub fn record(&mut self, resource: ResourceKind, value: u64) {
        self.values.insert(resource, value);
    }
}

/// Stateless helper for consistent structured budget checks.
pub struct BudgetCheck;

impl BudgetCheck {
    /// Accepts `actual <= limit` and returns a structured deterministic error otherwise.
    pub fn ensure(
        resource: ResourceKind,
        limit: u64,
        actual: u64,
        context: impl Into<String>,
    ) -> AgentResult<()> {
        if actual <= limit {
            return Ok(());
        }
        let context = context.into();
        Err(AgentError::new(
            ErrorCode::ResourceLimitExceeded,
            format!("resource limit exceeded for {resource:?}"),
        )
        .with_types(json!(limit), json!(actual))
        .with_detail("resource", json!(resource))
        .with_detail("configured_limit", limit)
        .with_detail("attempted", actual)
        .with_detail("context", context)
        .with_repair("reduce the request or raise the configured interactive limit"))
    }

    /// Checks an observed value against the corresponding configured limit.
    pub fn against(
        limits: &ResourceLimits,
        resource: ResourceKind,
        actual: u64,
        context: impl Into<String>,
    ) -> AgentResult<()> {
        Self::ensure(resource, limits.limit(resource), actual, context)
    }
}
