//! Central deterministic resource-budget model.

use crate::diagnostics::{AgentError, AgentResult, ErrorCode};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::BTreeMap;

/// A bounded resource category shared across AgentIR layers.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResourceKind {
    /// Encoded bytes in one JSONL request.
    JsonlRequestBytes,
    /// Actions in one atomic transaction.
    ActionsPerTransaction,
    /// Declared dimensions in one program.
    DimensionsPerProgram,
    /// Top-level operations in one program.
    OperationsPerProgram,
    /// SSA values in one program.
    ValuesPerProgram,
    /// Typed holes in one program.
    HolesPerProgram,
    /// Proof obligations in one program.
    ObligationsPerProgram,
    /// Shape constraints in one program.
    ConstraintsPerProgram,
    /// Block arguments in one inline region.
    RegionArguments,
    /// Local operations in one inline region.
    RegionOperations,
    /// Operands on one top-level or region operation.
    OperandsPerOperation,
    /// Encoded JSON bytes in one action or operation attribute map.
    AttributeJsonBytes,
    /// Maximum structural JSON nesting depth.
    JsonNestingDepth,
    /// Named outputs in one program.
    OutputCount,
    /// Encoded bytes in one workspace archive.
    ArchiveBytes,
    /// Immutable revisions in one archive.
    RevisionsPerArchive,
    /// Replayable events in one archive.
    EventsPerArchive,
    /// Total ActionIR actions replayed from one archive.
    ActionsReplayedPerArchive,
    /// Bytes in exact-state or semantic canonical output.
    CanonicalOutputBytes,
    /// Elements in one evaluation tensor.
    EvaluationTensorElements,
    /// Total tensor elements materialized during one evaluation.
    TotalEvaluationElements,
    /// Nodes/items generated by one property or fuzz case.
    GeneratedCaseSize,
    /// Implementation candidates retained by one workspace.
    CandidatesPerWorkspace,
    /// Immutable candidate revisions retained by one workspace.
    CandidateRevisionsPerWorkspace,
    /// Candidate events retained by one archive.
    CandidateEventsPerArchive,
    /// Candidate actions in one atomic transaction.
    CandidateActionsPerTransaction,
    /// Top-level operations in one ImplIR graph.
    ImplOperations,
    /// SSA values in one ImplIR graph.
    ImplValues,
    /// Candidate branch identities retained by one workspace.
    CandidateBranches,
    /// Rewrite matches emitted by one continuation.
    RewriteMatchesPerContinuation,
    /// Trusted rewrite steps in one candidate proof chain.
    RewriteStepsPerCandidate,
    /// Evidence records retained by one workspace.
    EvidenceRecords,
    /// Encoded EvidenceIR bytes retained by one workspace.
    EvidenceBytes,
    /// Open candidate equivalence obligations.
    OpenEquivalenceObligations,
    /// Deterministic cases in one differential validation.
    DifferentialCases,
    /// Tensor elements generated by one differential validation.
    DifferentialTensorElements,
    /// Exact or semantic candidate canonical bytes.
    CandidateCanonicalBytes,
    /// Exact speculative/guarded candidate canonical-v2 bytes.
    CandidateCanonicalV2Bytes,
    /// Nodes/items generated by one candidate property case.
    GeneratedCandidateCaseSize,
    /// Persistent proposal records retained by one workspace.
    ProposalsPerWorkspace,
    /// Persistent proposals reachable on one candidate branch.
    ProposalsPerCandidate,
    /// Proposal actions in one speculative transaction.
    ProposalActionsPerTransaction,
    /// Operations in one proposed replacement fragment.
    ProposalFragmentOperations,
    /// Values in one proposed replacement fragment.
    ProposalFragmentValues,
    /// Encoded normalized proposal bytes.
    ProposalEncodedBytes,
    /// Speculative nodes retained on one candidate branch.
    SpeculativeNodesPerCandidate,
    /// Consecutive speculative depth on one branch.
    SpeculativeDepthPerBranch,
    /// Unknown actions retained on one branch.
    UnknownActionsPerBranch,
    /// Ordered open/unsupported proof-debt items.
    OpenProofDebtObligations,
    /// Translation-validation attempts retained by one workspace.
    TranslationValidationAttempts,
    /// Deterministic validator work units in one check.
    TranslationValidationWorkUnits,
    /// Guarded candidate revisions retained by one workspace.
    GuardedCandidates,
    /// Nodes needed to compute one guard predicate.
    GuardDependencyNodes,
    /// Maximum recursive fallback depth.
    FallbackDepth,
    /// Encoded bytes in one deterministic counterexample.
    CounterexampleBytes,
    /// Candidate-semantics-v2 events retained by one archive.
    CandidateSemanticsV2Events,
    /// Generated speculative property-case size.
    GeneratedSpeculativeCaseSize,
    /// Persistent exact equality spaces retained by one workspace.
    EqualitySpacesPerWorkspace,
    /// Immutable equality revisions retained by one workspace.
    EqualityRevisionsPerWorkspace,
    /// Semantic implementation nodes retained by one equality space.
    EqualityNodesPerSpace,
    /// Trusted proof edges retained by one equality space.
    EqualityEdgesPerSpace,
    /// Pending deterministic node work items retained by one equality space.
    EqualityPendingWorkItems,
    /// Equality node work items expanded by one request.
    EqualityExpansionStepsPerRequest,
    /// Caller fuel accepted by one saturation request.
    EqualitySaturationFuel,
    /// Trusted production matches enumerated for one equality node.
    EqualityMatchesPerNode,
    /// Maximum edge depth explored by one canonical proof explanation.
    EqualityExplanationDepth,
    /// Maximum trusted edges returned by one equality proof path.
    EqualityProofPathEdges,
    /// Maximum trusted rewrite steps replayed by one materialization.
    EqualityMaterializationSteps,
    /// Stage 2C optimization events retained by one workspace/archive.
    EqualityEvents,
    /// Bytes in one equality exact-state canonical encoding.
    EqualityCanonicalBytes,
    /// Bytes attributed to equality state in one archive.
    EqualityArchiveBytes,
    /// Reference evaluation cases for equality nodes.
    EqualityEvaluationCases,
    /// Reference evaluation elements for equality nodes.
    EqualityEvaluationElements,
    /// Exact candidate canonical-v3 bytes.
    CandidateCanonicalV3Bytes,
    /// Persistent memory plans retained by one workspace.
    MemoryPlansPerWorkspace,
    /// Immutable memory revisions retained by one workspace.
    MemoryRevisionsPerWorkspace,
    /// Replayable memory events retained by one workspace/archive.
    MemoryEvents,
    /// Typed buffers retained by one memory revision.
    MemoryBuffersPerPlan,
    /// Memory operations retained by one memory revision.
    MemoryOperationsPerPlan,
    /// Typed accesses retained by one memory revision.
    MemoryAccessesPerPlan,
    /// Alias domains retained by one memory revision.
    MemoryAliasDomains,
    /// Alias facts retained by one memory revision.
    MemoryAliasFacts,
    /// Definition, last-use, and escape points retained by one memory revision.
    MemoryLifetimePoints,
    /// Lifetime use points retained by one memory revision.
    MemoryLifetimeUses,
    /// Memory correctness obligations retained by one memory revision.
    MemoryObligations,
    /// Reuse actions attempted by one memory transaction.
    MemoryReuseAttempts,
    /// Dependencies of one compiler-owned memory guard.
    MemoryGuardDependencies,
    /// Maximum nested compiler-owned memory guard depth.
    MemoryGuardDepth,
    /// Maximum nested guarded memory fallback depth.
    MemoryFallbackDepth,
    /// Tensor rank and stride entries in one buffer layout.
    MemoryLayoutEntries,
    /// Static abstract allocation bytes for one buffer.
    MemoryAllocationBytesPerBuffer,
    /// Total static abstract allocation bytes for one memory revision.
    MemoryTotalAllocationBytes,
    /// Bytes in one canonical exact MemoryIR state.
    MemoryCanonicalBytes,
    /// Bytes attributed to MemoryIR in one archive.
    MemoryArchiveBytes,
    /// Elements processed by one reference memory evaluation.
    MemoryEvaluationElements,
    /// Events retained in one deterministic reference memory trace.
    MemoryTraceEvents,
    /// Bytes retained in one deterministic reference memory trace.
    MemoryTraceBytes,
    /// Generated MemoryIR property/mutation case size.
    GeneratedMemoryCaseSize,
}

/// Configurable interactive limits. These values never enter graph or archive hashes.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResourceLimits {
    /// Maximum encoded JSONL request bytes.
    pub jsonl_request_bytes: u64,
    /// Maximum actions in one transaction.
    pub actions_per_transaction: u64,
    /// Maximum declared dimensions in a program.
    pub dimensions_per_program: u64,
    /// Maximum top-level operations in a program.
    pub operations_per_program: u64,
    /// Maximum SSA values in a program.
    pub values_per_program: u64,
    /// Maximum typed holes in a program.
    pub holes_per_program: u64,
    /// Maximum proof obligations in a program.
    pub obligations_per_program: u64,
    /// Maximum retained constraints in a program.
    pub constraints_per_program: u64,
    /// Maximum block arguments in one region.
    pub region_arguments: u64,
    /// Maximum local operations in one region.
    pub region_operations: u64,
    /// Maximum operands on one operation.
    pub operands_per_operation: u64,
    /// Maximum encoded attribute bytes on one operation.
    pub attribute_json_bytes: u64,
    /// Maximum JSON nesting depth.
    pub json_nesting_depth: u64,
    /// Maximum named outputs in a program.
    pub output_count: u64,
    /// Maximum encoded archive bytes.
    pub archive_bytes: u64,
    /// Maximum revisions in an archive.
    pub revisions_per_archive: u64,
    /// Maximum events in an archive.
    pub events_per_archive: u64,
    /// Maximum actions replayed from an archive.
    pub actions_replayed_per_archive: u64,
    /// Maximum canonical encoding bytes.
    pub canonical_output_bytes: u64,
    /// Maximum elements in one evaluation tensor.
    pub evaluation_tensor_elements: u64,
    /// Maximum total tensor elements materialized by one evaluation.
    pub total_evaluation_elements: u64,
    /// Maximum generated property/fuzz case size.
    pub generated_case_size: u64,
    /// Maximum implementation candidates in one workspace.
    pub candidates_per_workspace: u64,
    /// Maximum immutable candidate revisions in one workspace.
    pub candidate_revisions_per_workspace: u64,
    /// Maximum candidate events in one archive.
    pub candidate_events_per_archive: u64,
    /// Maximum actions in one candidate transaction.
    pub candidate_actions_per_transaction: u64,
    /// Maximum operations in one ImplIR graph.
    pub impl_operations: u64,
    /// Maximum values in one ImplIR graph.
    pub impl_values: u64,
    /// Maximum candidate branch identities in one workspace.
    pub candidate_branches: u64,
    /// Maximum emitted rewrite matches in one continuation.
    pub rewrite_matches_per_continuation: u64,
    /// Maximum trusted rewrite steps in one candidate.
    pub rewrite_steps_per_candidate: u64,
    /// Maximum evidence records in one workspace.
    pub evidence_records: u64,
    /// Maximum encoded evidence bytes in one workspace.
    pub evidence_bytes: u64,
    /// Maximum open equivalence obligations in one workspace.
    pub open_equivalence_obligations: u64,
    /// Maximum cases in one differential validation.
    pub differential_cases: u64,
    /// Maximum generated tensor elements in one differential validation.
    pub differential_tensor_elements: u64,
    /// Maximum bytes in candidate canonical encodings.
    pub candidate_canonical_bytes: u64,
    /// Maximum bytes in speculative/guarded candidate canonical-v2 encodings.
    pub candidate_canonical_v2_bytes: u64,
    /// Maximum nodes/items in one generated candidate/property case.
    pub generated_candidate_case_size: u64,
    /// Maximum persistent proposal records in one workspace.
    pub proposals_per_workspace: u64,
    /// Maximum proposals in one candidate history.
    pub proposals_per_candidate: u64,
    /// Maximum actions in one proposal transaction.
    pub proposal_actions_per_transaction: u64,
    /// Maximum operations in one proposed fragment.
    pub proposal_fragment_operations: u64,
    /// Maximum values in one proposed fragment.
    pub proposal_fragment_values: u64,
    /// Maximum encoded normalized proposal bytes.
    pub proposal_encoded_bytes: u64,
    /// Maximum speculative nodes in one candidate.
    pub speculative_nodes_per_candidate: u64,
    /// Maximum speculative depth on one branch.
    pub speculative_depth_per_branch: u64,
    /// Maximum unknown actions on one branch.
    pub unknown_actions_per_branch: u64,
    /// Maximum open or unsupported proof-debt obligations.
    pub open_proof_debt_obligations: u64,
    /// Maximum translation-validation attempts in one workspace.
    pub translation_validation_attempts: u64,
    /// Maximum deterministic work units in one translation check.
    pub translation_validation_work_units: u64,
    /// Maximum guarded candidate revisions in one workspace.
    pub guarded_candidates: u64,
    /// Maximum dependency nodes for one guard.
    pub guard_dependency_nodes: u64,
    /// Maximum guarded fallback recursion depth.
    pub fallback_depth: u64,
    /// Maximum encoded bytes in one counterexample.
    pub counterexample_bytes: u64,
    /// Maximum candidate-semantics-v2 events per archive.
    pub candidate_semantics_v2_events: u64,
    /// Maximum generated speculative property-case size.
    pub generated_speculative_case_size: u64,
    /// Maximum exact equality spaces retained by one workspace.
    pub equality_spaces_per_workspace: u64,
    /// Maximum immutable equality revisions retained by one workspace.
    pub equality_revisions_per_workspace: u64,
    /// Maximum semantic nodes retained by one equality space.
    pub equality_nodes_per_space: u64,
    /// Maximum trusted edges retained by one equality space.
    pub equality_edges_per_space: u64,
    /// Maximum pending node work items retained by one equality space.
    pub equality_pending_work_items: u64,
    /// Maximum node work items expanded by one request.
    pub equality_expansion_steps_per_request: u64,
    /// Maximum explicit caller fuel for saturation.
    pub equality_saturation_fuel: u64,
    /// Maximum production matches inspected for one node.
    pub equality_matches_per_node: u64,
    /// Maximum explanation search depth.
    pub equality_explanation_depth: u64,
    /// Maximum edges in one returned proof path.
    pub equality_proof_path_edges: u64,
    /// Maximum rewrite steps in one materialization.
    pub equality_materialization_steps: u64,
    /// Maximum Stage 2C optimization events.
    pub equality_events: u64,
    /// Maximum equality canonical bytes.
    pub equality_canonical_bytes: u64,
    /// Maximum equality bytes retained by one archive.
    pub equality_archive_bytes: u64,
    /// Maximum cases consumed by one equality evaluation request.
    pub equality_evaluation_cases: u64,
    /// Maximum elements consumed by one equality evaluation request.
    pub equality_evaluation_elements: u64,
    /// Maximum candidate canonical-v3 bytes.
    pub candidate_canonical_v3_bytes: u64,
    /// Maximum persistent memory plans in one workspace.
    pub memory_plans_per_workspace: u64,
    /// Maximum immutable memory revisions in one workspace.
    pub memory_revisions_per_workspace: u64,
    /// Maximum replayable memory events.
    pub memory_events: u64,
    /// Maximum typed buffers in one memory revision.
    pub memory_buffers_per_plan: u64,
    /// Maximum memory operations in one memory revision.
    pub memory_operations_per_plan: u64,
    /// Maximum explicit typed accesses in one memory revision.
    pub memory_accesses_per_plan: u64,
    /// Maximum alias domains in one memory revision.
    pub memory_alias_domains: u64,
    /// Maximum alias facts in one memory revision.
    pub memory_alias_facts: u64,
    /// Maximum lifetime definition/last-use/escape points in one memory revision.
    pub memory_lifetime_points: u64,
    /// Maximum lifetime use points in one memory revision.
    pub memory_lifetime_uses: u64,
    /// Maximum memory obligations in one memory revision.
    pub memory_obligations: u64,
    /// Maximum reuse attempts in one transaction.
    pub memory_reuse_attempts: u64,
    /// Maximum dependencies in one compiler-owned memory guard.
    pub memory_guard_dependencies: u64,
    /// Maximum nested compiler-owned memory guard depth.
    pub memory_guard_depth: u64,
    /// Maximum nested memory fallback depth.
    pub memory_fallback_depth: u64,
    /// Maximum rank/stride entries in one buffer layout.
    pub memory_layout_entries: u64,
    /// Maximum static abstract bytes in one buffer.
    pub memory_allocation_bytes_per_buffer: u64,
    /// Maximum total static abstract allocation bytes.
    pub memory_total_allocation_bytes: u64,
    /// Maximum canonical MemoryIR bytes.
    pub memory_canonical_bytes: u64,
    /// Maximum archive bytes attributed to MemoryIR.
    pub memory_archive_bytes: u64,
    /// Maximum elements processed by one memory evaluation.
    pub memory_evaluation_elements: u64,
    /// Maximum events in one deterministic memory trace.
    pub memory_trace_events: u64,
    /// Maximum encoded bytes in one deterministic memory trace.
    pub memory_trace_bytes: u64,
    /// Maximum generated MemoryIR property-case size.
    pub generated_memory_case_size: u64,
}

impl Default for ResourceLimits {
    fn default() -> Self {
        Self {
            jsonl_request_bytes: 1024 * 1024,
            actions_per_transaction: 4_096,
            dimensions_per_program: 4_096,
            operations_per_program: 100_000,
            values_per_program: 120_000,
            holes_per_program: 10_000,
            obligations_per_program: 100_000,
            constraints_per_program: 20_000,
            region_arguments: 64,
            region_operations: 1_024,
            operands_per_operation: 64,
            attribute_json_bytes: 256 * 1024,
            json_nesting_depth: 128,
            output_count: 1_024,
            archive_bytes: 64 * 1024 * 1024,
            revisions_per_archive: 100_000,
            events_per_archive: 100_000,
            actions_replayed_per_archive: 1_000_000,
            canonical_output_bytes: 64 * 1024 * 1024,
            evaluation_tensor_elements: 10_000_000,
            total_evaluation_elements: 50_000_000,
            generated_case_size: 10_000,
            candidates_per_workspace: 10_000,
            candidate_revisions_per_workspace: 100_000,
            candidate_events_per_archive: 100_000,
            candidate_actions_per_transaction: 1_024,
            impl_operations: 100_000,
            impl_values: 120_000,
            candidate_branches: 10_000,
            rewrite_matches_per_continuation: 10_000,
            rewrite_steps_per_candidate: 10_000,
            evidence_records: 100_000,
            evidence_bytes: 64 * 1024 * 1024,
            open_equivalence_obligations: 10_000,
            differential_cases: 256,
            differential_tensor_elements: 1_000_000,
            candidate_canonical_bytes: 64 * 1024 * 1024,
            candidate_canonical_v2_bytes: 64 * 1024 * 1024,
            generated_candidate_case_size: 10_000,
            proposals_per_workspace: 100_000,
            proposals_per_candidate: 1_024,
            proposal_actions_per_transaction: 1_024,
            proposal_fragment_operations: 1_024,
            proposal_fragment_values: 1_024,
            proposal_encoded_bytes: 1024 * 1024,
            speculative_nodes_per_candidate: 10_000,
            speculative_depth_per_branch: 128,
            unknown_actions_per_branch: 128,
            open_proof_debt_obligations: 128,
            translation_validation_attempts: 100_000,
            translation_validation_work_units: 100_000,
            guarded_candidates: 10_000,
            guard_dependency_nodes: 1_024,
            fallback_depth: 16,
            counterexample_bytes: 1024 * 1024,
            candidate_semantics_v2_events: 100_000,
            generated_speculative_case_size: 10_000,
            equality_spaces_per_workspace: 1_024,
            equality_revisions_per_workspace: 100_000,
            equality_nodes_per_space: 10_000,
            equality_edges_per_space: 100_000,
            equality_pending_work_items: 10_000,
            equality_expansion_steps_per_request: 1_024,
            equality_saturation_fuel: 10_000,
            equality_matches_per_node: 10_000,
            equality_explanation_depth: 1_024,
            equality_proof_path_edges: 1_024,
            equality_materialization_steps: 1_024,
            equality_events: 100_000,
            equality_canonical_bytes: 64 * 1024 * 1024,
            equality_archive_bytes: 64 * 1024 * 1024,
            equality_evaluation_cases: 1,
            equality_evaluation_elements: 50_000_000,
            candidate_canonical_v3_bytes: 64 * 1024 * 1024,
            memory_plans_per_workspace: 1_024,
            memory_revisions_per_workspace: 100_000,
            memory_events: 100_000,
            memory_buffers_per_plan: 100_000,
            memory_operations_per_plan: 100_000,
            memory_accesses_per_plan: 500_000,
            memory_alias_domains: 100_000,
            memory_alias_facts: 500_000,
            memory_lifetime_points: 500_000,
            memory_lifetime_uses: 500_000,
            memory_obligations: 100_000,
            memory_reuse_attempts: 1_024,
            memory_guard_dependencies: 1_024,
            memory_guard_depth: 16,
            memory_fallback_depth: 16,
            memory_layout_entries: 1_024,
            memory_allocation_bytes_per_buffer: 8 * 1024 * 1024 * 1024,
            memory_total_allocation_bytes: 64 * 1024 * 1024 * 1024,
            memory_canonical_bytes: 64 * 1024 * 1024,
            memory_archive_bytes: 64 * 1024 * 1024,
            memory_evaluation_elements: 50_000_000,
            memory_trace_events: 1_000_000,
            memory_trace_bytes: 64 * 1024 * 1024,
            generated_memory_case_size: 10_000,
        }
    }
}

impl ResourceLimits {
    /// Returns non-configurable caps used while decoding and replaying archives.
    #[must_use]
    pub const fn hard_safety_caps() -> Self {
        Self {
            jsonl_request_bytes: 8 * 1024 * 1024,
            actions_per_transaction: 100_000,
            dimensions_per_program: 100_000,
            operations_per_program: 1_000_000,
            values_per_program: 1_200_000,
            holes_per_program: 100_000,
            obligations_per_program: 1_000_000,
            constraints_per_program: 200_000,
            region_arguments: 1_024,
            region_operations: 100_000,
            operands_per_operation: 4_096,
            attribute_json_bytes: 4 * 1024 * 1024,
            json_nesting_depth: 256,
            output_count: 100_000,
            archive_bytes: 64 * 1024 * 1024,
            revisions_per_archive: 250_000,
            events_per_archive: 250_000,
            actions_replayed_per_archive: 5_000_000,
            canonical_output_bytes: 128 * 1024 * 1024,
            evaluation_tensor_elements: 100_000_000,
            total_evaluation_elements: 500_000_000,
            generated_case_size: 100_000,
            candidates_per_workspace: 100_000,
            candidate_revisions_per_workspace: 250_000,
            candidate_events_per_archive: 250_000,
            candidate_actions_per_transaction: 100_000,
            impl_operations: 1_000_000,
            impl_values: 1_200_000,
            candidate_branches: 100_000,
            rewrite_matches_per_continuation: 100_000,
            rewrite_steps_per_candidate: 100_000,
            evidence_records: 1_000_000,
            evidence_bytes: 128 * 1024 * 1024,
            open_equivalence_obligations: 100_000,
            differential_cases: 10_000,
            differential_tensor_elements: 100_000_000,
            candidate_canonical_bytes: 128 * 1024 * 1024,
            candidate_canonical_v2_bytes: 128 * 1024 * 1024,
            generated_candidate_case_size: 100_000,
            proposals_per_workspace: 1_000_000,
            proposals_per_candidate: 100_000,
            proposal_actions_per_transaction: 100_000,
            proposal_fragment_operations: 100_000,
            proposal_fragment_values: 100_000,
            proposal_encoded_bytes: 8 * 1024 * 1024,
            speculative_nodes_per_candidate: 100_000,
            speculative_depth_per_branch: 1_024,
            unknown_actions_per_branch: 1_024,
            open_proof_debt_obligations: 100_000,
            translation_validation_attempts: 1_000_000,
            translation_validation_work_units: 1_000_000,
            guarded_candidates: 100_000,
            guard_dependency_nodes: 100_000,
            fallback_depth: 64,
            counterexample_bytes: 8 * 1024 * 1024,
            candidate_semantics_v2_events: 250_000,
            generated_speculative_case_size: 100_000,
            equality_spaces_per_workspace: 100_000,
            equality_revisions_per_workspace: 250_000,
            equality_nodes_per_space: 100_000,
            equality_edges_per_space: 1_000_000,
            equality_pending_work_items: 100_000,
            equality_expansion_steps_per_request: 100_000,
            equality_saturation_fuel: 100_000,
            equality_matches_per_node: 100_000,
            equality_explanation_depth: 100_000,
            equality_proof_path_edges: 100_000,
            equality_materialization_steps: 100_000,
            equality_events: 250_000,
            equality_canonical_bytes: 128 * 1024 * 1024,
            equality_archive_bytes: 128 * 1024 * 1024,
            equality_evaluation_cases: 1,
            equality_evaluation_elements: 500_000_000,
            candidate_canonical_v3_bytes: 128 * 1024 * 1024,
            memory_plans_per_workspace: 100_000,
            memory_revisions_per_workspace: 250_000,
            memory_events: 250_000,
            memory_buffers_per_plan: 1_000_000,
            memory_operations_per_plan: 1_000_000,
            memory_accesses_per_plan: 5_000_000,
            memory_alias_domains: 1_000_000,
            memory_alias_facts: 5_000_000,
            memory_lifetime_points: 5_000_000,
            memory_lifetime_uses: 5_000_000,
            memory_obligations: 1_000_000,
            memory_reuse_attempts: 100_000,
            memory_guard_dependencies: 100_000,
            memory_guard_depth: 64,
            memory_fallback_depth: 64,
            memory_layout_entries: 4_096,
            memory_allocation_bytes_per_buffer: 64 * 1024 * 1024 * 1024,
            memory_total_allocation_bytes: 512 * 1024 * 1024 * 1024,
            memory_canonical_bytes: 128 * 1024 * 1024,
            memory_archive_bytes: 128 * 1024 * 1024,
            memory_evaluation_elements: 500_000_000,
            memory_trace_events: 10_000_000,
            memory_trace_bytes: 128 * 1024 * 1024,
            generated_memory_case_size: 100_000,
        }
    }

    /// Returns the configured limit for one resource kind.
    #[must_use]
    pub const fn limit(&self, resource: ResourceKind) -> u64 {
        match resource {
            ResourceKind::JsonlRequestBytes => self.jsonl_request_bytes,
            ResourceKind::ActionsPerTransaction => self.actions_per_transaction,
            ResourceKind::DimensionsPerProgram => self.dimensions_per_program,
            ResourceKind::OperationsPerProgram => self.operations_per_program,
            ResourceKind::ValuesPerProgram => self.values_per_program,
            ResourceKind::HolesPerProgram => self.holes_per_program,
            ResourceKind::ObligationsPerProgram => self.obligations_per_program,
            ResourceKind::ConstraintsPerProgram => self.constraints_per_program,
            ResourceKind::RegionArguments => self.region_arguments,
            ResourceKind::RegionOperations => self.region_operations,
            ResourceKind::OperandsPerOperation => self.operands_per_operation,
            ResourceKind::AttributeJsonBytes => self.attribute_json_bytes,
            ResourceKind::JsonNestingDepth => self.json_nesting_depth,
            ResourceKind::OutputCount => self.output_count,
            ResourceKind::ArchiveBytes => self.archive_bytes,
            ResourceKind::RevisionsPerArchive => self.revisions_per_archive,
            ResourceKind::EventsPerArchive => self.events_per_archive,
            ResourceKind::ActionsReplayedPerArchive => self.actions_replayed_per_archive,
            ResourceKind::CanonicalOutputBytes => self.canonical_output_bytes,
            ResourceKind::EvaluationTensorElements => self.evaluation_tensor_elements,
            ResourceKind::TotalEvaluationElements => self.total_evaluation_elements,
            ResourceKind::GeneratedCaseSize => self.generated_case_size,
            ResourceKind::CandidatesPerWorkspace => self.candidates_per_workspace,
            ResourceKind::CandidateRevisionsPerWorkspace => self.candidate_revisions_per_workspace,
            ResourceKind::CandidateEventsPerArchive => self.candidate_events_per_archive,
            ResourceKind::CandidateActionsPerTransaction => self.candidate_actions_per_transaction,
            ResourceKind::ImplOperations => self.impl_operations,
            ResourceKind::ImplValues => self.impl_values,
            ResourceKind::CandidateBranches => self.candidate_branches,
            ResourceKind::RewriteMatchesPerContinuation => self.rewrite_matches_per_continuation,
            ResourceKind::RewriteStepsPerCandidate => self.rewrite_steps_per_candidate,
            ResourceKind::EvidenceRecords => self.evidence_records,
            ResourceKind::EvidenceBytes => self.evidence_bytes,
            ResourceKind::OpenEquivalenceObligations => self.open_equivalence_obligations,
            ResourceKind::DifferentialCases => self.differential_cases,
            ResourceKind::DifferentialTensorElements => self.differential_tensor_elements,
            ResourceKind::CandidateCanonicalBytes => self.candidate_canonical_bytes,
            ResourceKind::CandidateCanonicalV2Bytes => self.candidate_canonical_v2_bytes,
            ResourceKind::GeneratedCandidateCaseSize => self.generated_candidate_case_size,
            ResourceKind::ProposalsPerWorkspace => self.proposals_per_workspace,
            ResourceKind::ProposalsPerCandidate => self.proposals_per_candidate,
            ResourceKind::ProposalActionsPerTransaction => self.proposal_actions_per_transaction,
            ResourceKind::ProposalFragmentOperations => self.proposal_fragment_operations,
            ResourceKind::ProposalFragmentValues => self.proposal_fragment_values,
            ResourceKind::ProposalEncodedBytes => self.proposal_encoded_bytes,
            ResourceKind::SpeculativeNodesPerCandidate => self.speculative_nodes_per_candidate,
            ResourceKind::SpeculativeDepthPerBranch => self.speculative_depth_per_branch,
            ResourceKind::UnknownActionsPerBranch => self.unknown_actions_per_branch,
            ResourceKind::OpenProofDebtObligations => self.open_proof_debt_obligations,
            ResourceKind::TranslationValidationAttempts => self.translation_validation_attempts,
            ResourceKind::TranslationValidationWorkUnits => self.translation_validation_work_units,
            ResourceKind::GuardedCandidates => self.guarded_candidates,
            ResourceKind::GuardDependencyNodes => self.guard_dependency_nodes,
            ResourceKind::FallbackDepth => self.fallback_depth,
            ResourceKind::CounterexampleBytes => self.counterexample_bytes,
            ResourceKind::CandidateSemanticsV2Events => self.candidate_semantics_v2_events,
            ResourceKind::GeneratedSpeculativeCaseSize => self.generated_speculative_case_size,
            ResourceKind::EqualitySpacesPerWorkspace => self.equality_spaces_per_workspace,
            ResourceKind::EqualityRevisionsPerWorkspace => self.equality_revisions_per_workspace,
            ResourceKind::EqualityNodesPerSpace => self.equality_nodes_per_space,
            ResourceKind::EqualityEdgesPerSpace => self.equality_edges_per_space,
            ResourceKind::EqualityPendingWorkItems => self.equality_pending_work_items,
            ResourceKind::EqualityExpansionStepsPerRequest => {
                self.equality_expansion_steps_per_request
            }
            ResourceKind::EqualitySaturationFuel => self.equality_saturation_fuel,
            ResourceKind::EqualityMatchesPerNode => self.equality_matches_per_node,
            ResourceKind::EqualityExplanationDepth => self.equality_explanation_depth,
            ResourceKind::EqualityProofPathEdges => self.equality_proof_path_edges,
            ResourceKind::EqualityMaterializationSteps => self.equality_materialization_steps,
            ResourceKind::EqualityEvents => self.equality_events,
            ResourceKind::EqualityCanonicalBytes => self.equality_canonical_bytes,
            ResourceKind::EqualityArchiveBytes => self.equality_archive_bytes,
            ResourceKind::EqualityEvaluationCases => self.equality_evaluation_cases,
            ResourceKind::EqualityEvaluationElements => self.equality_evaluation_elements,
            ResourceKind::CandidateCanonicalV3Bytes => self.candidate_canonical_v3_bytes,
            ResourceKind::MemoryPlansPerWorkspace => self.memory_plans_per_workspace,
            ResourceKind::MemoryRevisionsPerWorkspace => self.memory_revisions_per_workspace,
            ResourceKind::MemoryEvents => self.memory_events,
            ResourceKind::MemoryBuffersPerPlan => self.memory_buffers_per_plan,
            ResourceKind::MemoryOperationsPerPlan => self.memory_operations_per_plan,
            ResourceKind::MemoryAccessesPerPlan => self.memory_accesses_per_plan,
            ResourceKind::MemoryAliasDomains => self.memory_alias_domains,
            ResourceKind::MemoryAliasFacts => self.memory_alias_facts,
            ResourceKind::MemoryLifetimePoints => self.memory_lifetime_points,
            ResourceKind::MemoryLifetimeUses => self.memory_lifetime_uses,
            ResourceKind::MemoryObligations => self.memory_obligations,
            ResourceKind::MemoryReuseAttempts => self.memory_reuse_attempts,
            ResourceKind::MemoryGuardDependencies => self.memory_guard_dependencies,
            ResourceKind::MemoryGuardDepth => self.memory_guard_depth,
            ResourceKind::MemoryFallbackDepth => self.memory_fallback_depth,
            ResourceKind::MemoryLayoutEntries => self.memory_layout_entries,
            ResourceKind::MemoryAllocationBytesPerBuffer => self.memory_allocation_bytes_per_buffer,
            ResourceKind::MemoryTotalAllocationBytes => self.memory_total_allocation_bytes,
            ResourceKind::MemoryCanonicalBytes => self.memory_canonical_bytes,
            ResourceKind::MemoryArchiveBytes => self.memory_archive_bytes,
            ResourceKind::MemoryEvaluationElements => self.memory_evaluation_elements,
            ResourceKind::MemoryTraceEvents => self.memory_trace_events,
            ResourceKind::MemoryTraceBytes => self.memory_trace_bytes,
            ResourceKind::GeneratedMemoryCaseSize => self.generated_memory_case_size,
        }
    }
}

/// Deterministic observed resource usage keyed by category.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResourceUsage {
    /// Observed or projected values.
    pub values: BTreeMap<ResourceKind, u64>,
}

impl ResourceUsage {
    /// Records one observed or projected resource value.
    pub fn record(&mut self, resource: ResourceKind, value: u64) {
        self.values.insert(resource, value);
    }
}

/// Stateless helper for consistent structured budget checks.
pub struct BudgetCheck;

impl BudgetCheck {
    /// Accepts `actual <= limit` and returns a structured deterministic error otherwise.
    pub fn ensure(
        resource: ResourceKind,
        limit: u64,
        actual: u64,
        context: impl Into<String>,
    ) -> AgentResult<()> {
        if actual <= limit {
            return Ok(());
        }
        let context = context.into();
        Err(AgentError::new(
            ErrorCode::ResourceLimitExceeded,
            format!("resource limit exceeded for {resource:?}"),
        )
        .with_types(json!(limit), json!(actual))
        .with_detail("resource", json!(resource))
        .with_detail("configured_limit", limit)
        .with_detail("attempted", actual)
        .with_detail("context", context)
        .with_repair("reduce the request or raise the configured interactive limit"))
    }

    /// Checks an observed value against the corresponding configured limit.
    pub fn against(
        limits: &ResourceLimits,
        resource: ResourceKind,
        actual: u64,
        context: impl Into<String>,
    ) -> AgentResult<()> {
        Self::ensure(resource, limits.limit(resource), actual, context)
    }
}
